import unittest
import tempfile
from mailmerge import MailMerge


class TestSplitMerge(unittest.TestCase):
    def test(self):
        """
        Test the case when Word splits a MergeField w:instrText into several pieces
        (Note the test document is a valid word document generated by Word 2007)
        """
        document = MailMerge('tests/test_split_merge.docx')
        self.assertEquals(document.get_merge_fields(),
                          set(['name_pinyin', 'name', 'semester',
                               'academic_year', 'date']))

        with tempfile.NamedTemporaryFile() as outfile:
            document.write(outfile)
